version: "3.8"

services:
  traefik:
    environment:
      - CLOUDFLARE_EMAIL=florian@nextstopbern.com
      - CLOUDFLARE_API_KEY=a7e80b68036e69c316bf1a41e99e7bb3740d7
    labels:
      traefik.docker.network: "traefik-net"
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: "https"
      traefik.http.routers.traefik.middlewares: "traefikAuth@file,default@file"
      traefik.http.routers.traefik.rule: "Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`) || Host(`teleport.bookingboost.ch`)" # [Attention]
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.tls.certresolver: "letsEncrypt"
      traefik.http.routers.traefik.tls.options: "modern@file"
      traefik.http.routers.traefik.tls: "true"
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.http.services.traefik.loadbalancer.sticky.cookie.httpOnly: "true"
      traefik.http.services.traefik.loadbalancer.sticky.cookie.secure: "true"
      # Schedule Traefik on the Swarm manager nodes, as the Swarm API is only exposed on the manager nodes
      # See https://docs.traefik.io/providers/docker/#docker-api-access_1
    # Published on https://hub.docker.com/_/traefik?tab=tags
    image: traefik:v2.10                                                     # See https://github.com/containous/traefik/releases
    networks:
      - traefik-net
    ports:
      # - 80:80
      # - 443:443
      # To be able to listen on port 80 (http)
      - mode: host
        published: 80
        target: 80
      # To be able to listen on port 443 (https)
      - mode: host
        published: 443
        target: 443
    volumes:
      - ./localtime:/etc/localtime:ro                                        # Set the container timezone by sharing the read-only localtime
      - ./config/dynamic_config.yml:/etc/traefik/config.yml:ro            # Set the dynamic configuration for the file provider
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro          # Set the static configuration
      - ./cert:/etc/traefik/acme                                      # Set the location where my ACME certificates are saved to
      - /var/run/docker.sock:/var/run/docker.sock:ro                            # Give access to the UNIX Docker socket
  
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      traefik.docker.network: "traefik-net"
      traefik.enable: "true"
      traefik.http.routers.whoami.entrypoints: "https"
      traefik.http.routers.whoami.middlewares: "default@file"
      traefik.http.routers.whoami.rule: "Host(`whoami.bookingboost.ch`)"
      traefik.http.routers.whoami.tls.certresolver: "letsEncrypt"
      traefik.http.routers.whoami.tls.options: "modern@file"
      traefik.http.routers.whoami.tls: "true"
    networks:
      - traefik-net
networks:
  traefik-net:
    external: true 